site_name: DMFF
nav:
  - Home: index.md
  - User Guide:
    - 1. Introduction: user_guide/introduction.md
    - 2. Installation: user_guide/installation.md
    - 3. Theory: user_guide/theory.md
    - 4. Get Started: user_guide/tutorial.md
    - 5. HOW TO - xml file: user_guide/xml_spec.md
    
  - Developer Guide:
    - 1. Introduction: dev_guide/introduction.md
    - 2. Architecture: dev_guide/arch.md
    - 3. Convention: dev_guide/convention.md
    - 4. Write Docs: dev_guide/write_docs.md

  - Modules:
    - ADMP: 
      - Introduction: admp/readme.md
      - Theory: user_guide/multipole_pme.md
      - Frontends: admp/frontend.md
  - About: about.md

theme: readthedocs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

plugins:
- mkdocstrings:

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
